name: adonis-boilerplate

services:
    redis:
        image: redis
        restart: always
        command:
            - /bin/sh
            - -c
            - redis-server
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 30s
            retries: 3
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 30s
            timeout: 30s
            retries: 3
