// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type StatusGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/general_controller.ts').default['status'], false>
}
type OpenapiGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/openapi_controller.ts').default['spec'], false>
}
type SignUpPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth_validator.ts')['userRegistrationValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['signUp'], true>
}
type SignInPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth_validator.ts')['credentialsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['signIn'], true>
}
type SigninBearerPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth_validator.ts')['credentialsValidatorForBearer']>>
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['signInForBearer'], true>
}
type AccessTokensGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/access_tokens_controller.ts').default['index'], false>
}
type AccessTokensPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/access_token_validator.ts')['accessTokenCreationValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/access_tokens_controller.ts').default['store'], true>
}
type AccesstokensRevokePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/access_tokens_controller.ts').default['revoke'], false>
}
type AccesstokensIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/access_tokens_controller.ts').default['show'], false>
}
type AccesstokensIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/access_token_validator.ts')['accessTokenUpdateValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/access_tokens_controller.ts').default['update'], true>
}
type AccesstokensIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/access_tokens_controller.ts').default['destroy'], false>
}
type RolesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/roles_controller.ts').default['index'], false>
}
type RolesBatchGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/role_validator.ts')['rolesShowBatchValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/roles_controller.ts').default['showBatch'], true>
}
type RolesIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/roles_controller.ts').default['show'], false>
}
type UsersMeGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['me'], false>
}
type UsersBatchGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/user_validator.ts')['usersShowBatchValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['showBatch'], true>
}
type UsersIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['show'], false>
}
type UsersIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/user_validator.ts')['userUpdateValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['update'], true>
}
type UsersIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['destroy'], false>
}
type SignOutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['signOut'], false>
}
type AdminAccesstokensGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/access_tokens_controller.ts').default['adminIndex'], false>
}
type AdminRolesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/roles_controller.ts').default['adminIndex'], false>
}
type AdminUsersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['adminIndex'], false>
}
type AdminRolesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/role_validator.ts')['roleCreationValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/roles_controller.ts').default['store'], true>
}
type AdminRolesIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/role_validator.ts')['roleUpdateValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/roles_controller.ts').default['update'], true>
}
type AdminRolesIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/roles_controller.ts').default['destroy'], false>
}
type AdminAccesstokensIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/access_tokens_controller.ts').default['index'], false>
}
type AdminAccesstokensIdPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/access_token_validator.ts')['accessTokenCreationValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/access_tokens_controller.ts').default['store'], true>
}
type AdminAccesstokensIdIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/access_tokens_controller.ts').default['show'], false>
}
type AdminAccesstokensIdIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/access_token_validator.ts')['accessTokenUpdateValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/access_tokens_controller.ts').default['update'], true>
}
type AdminAccesstokensIdIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/access_tokens_controller.ts').default['destroy'], false>
}
type AdminUsersIdLockPatch = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['lock'], false>
}
type AdminUsersIdUnlockPatch = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['unlock'], false>
}
export interface ApiDefinition {
  'status': {
    '$url': {
    };
    '$get': StatusGetHead;
    '$head': StatusGetHead;
  };
  'openapi': {
    '$url': {
    };
    '$get': OpenapiGetHead;
    '$head': OpenapiGetHead;
  };
  'sign-up': {
    '$url': {
    };
    '$post': SignUpPost;
  };
  'sign-in': {
    '$url': {
    };
    '$post': SignInPost;
    'bearer': {
      '$url': {
      };
      '$post': SigninBearerPost;
    };
  };
  'access-tokens': {
    '$url': {
    };
    '$get': AccessTokensGetHead;
    '$head': AccessTokensGetHead;
    '$post': AccessTokensPost;
    'revoke': {
      '$url': {
      };
      '$post': AccesstokensRevokePost;
    };
    ':access_token_id': {
      '$url': {
      };
      '$get': AccesstokensIdGetHead;
      '$head': AccesstokensIdGetHead;
      '$patch': AccesstokensIdPatch;
      '$delete': AccesstokensIdDelete;
    };
  };
  'roles': {
    '$url': {
    };
    '$get': RolesGetHead;
    '$head': RolesGetHead;
    'batch': {
      '$url': {
      };
      '$get': RolesBatchGetHead;
      '$head': RolesBatchGetHead;
    };
    ':role_id': {
      '$url': {
      };
      '$get': RolesIdGetHead;
      '$head': RolesIdGetHead;
    };
  };
  'users': {
    'me': {
      '$url': {
      };
      '$get': UsersMeGetHead;
      '$head': UsersMeGetHead;
    };
    'batch': {
      '$url': {
      };
      '$get': UsersBatchGetHead;
      '$head': UsersBatchGetHead;
    };
    ':user_id': {
      '$url': {
      };
      '$get': UsersIdGetHead;
      '$head': UsersIdGetHead;
      '$patch': UsersIdPatch;
      '$delete': UsersIdDelete;
    };
  };
  'sign-out': {
    '$url': {
    };
    '$post': SignOutPost;
  };
  'admin': {
    'access-tokens': {
      '$url': {
      };
      '$get': AdminAccesstokensGetHead;
      '$head': AdminAccesstokensGetHead;
      ':user_id': {
        '$url': {
        };
        '$get': AdminAccesstokensIdGetHead;
        '$head': AdminAccesstokensIdGetHead;
        '$post': AdminAccesstokensIdPost;
        ':access_token_id': {
          '$url': {
          };
          '$get': AdminAccesstokensIdIdGetHead;
          '$head': AdminAccesstokensIdIdGetHead;
          '$patch': AdminAccesstokensIdIdPatch;
          '$delete': AdminAccesstokensIdIdDelete;
        };
      };
    };
    'roles': {
      '$url': {
      };
      '$get': AdminRolesGetHead;
      '$head': AdminRolesGetHead;
      '$post': AdminRolesPost;
      ':role_id': {
        '$url': {
        };
        '$patch': AdminRolesIdPatch;
        '$delete': AdminRolesIdDelete;
      };
    };
    'users': {
      '$url': {
      };
      '$get': AdminUsersGetHead;
      '$head': AdminUsersGetHead;
      ':user_id': {
        'lock': {
          '$url': {
          };
          '$patch': AdminUsersIdLockPatch;
        };
        'unlock': {
          '$url': {
          };
          '$patch': AdminUsersIdUnlockPatch;
        };
      };
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
